version: '3'
services: 
  nginx:
    container_name: 'dao-swap'
    restart: always
    build: 
      context: .
    ports: 
      - 81:81
    volumes: 
      - ./nginx:/etc/nginx/conf.d
    networks: 
      - dao_swap
networks: 
  dao_swap:
    driver: bridge
